#
# EE 4374 Assignment 2 Makefile
# Author: Sebastian Gonzalez
#
all:
	gcc sgonzalez_argtok.h sgonzalez_exec.h sgonzalez_argtok.c sgonzalez_exec.c sgonzalez_prog2.c -o sgonzalez_prog2
clean:
	rm *.o; rm sgonzalez_prog2
